server:
  port: 8001
spring:
  application:
    name: ByteCinema
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.198.242.154:3306/bytecinema?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 'Chad@20021231'
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 121.40.204.51
    port: 6379
    #    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  mail:
    host: smtp.qq.com
    username: 2420811595@qq.com
    password: wfjyaomlkhnkdjjf
    port: 587
    default-encoding: UTF-8
    #其他参数
    properties:
      mail:
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
        #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

jwt:
  access-token:
    expiration: 3 * 360000 # 3h
  refresh-token:
    expiration: 7 * 24 * 360000 # 7天

mybatis-plus:
  type-aliases-package: org.chad.bytecinema.domain.po
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted # 配置逻辑删除字段
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler

#minio的配置信息，有需要再用
#minio:
#  endpoint: http://116.198.242.154:9090
#  accessKey: minio
#  secretKey: minio123
#  bucketName: cloudvault